sonar.projectKey=SnapSolve
sonar.sources=.
sonar.exclusions=services/whisperlive/**,**/build/**,**/.gradle/**,**/.kotlin/**,**/.idea/**,**/gradle/wrapper/**
sonar.host.url=http://localhost:9000
sonar.login=squ_960d358bb56fb9df43c524ccc94ddc7beac62273