from __future__ import annotations

import ctypes
import ctypes.wintypes
import json
import logging
import platform
import threading
from http.server import HTTPServer, BaseHTTPRequestHandler
from typing import Any, Optional
from urllib.parse import urlparse

import pyautogui

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Mouse blocker — blocks physical mouse while allowing pyautogui (injected)
# ---------------------------------------------------------------------------

# Windows constants for the low-level mouse hook.
WH_MOUSE_LL = 14
LLMHF_INJECTED = 0x00000001


class _MSLLHOOKSTRUCT(ctypes.Structure):
    """Mirror of the Win32 ``MSLLHOOKSTRUCT`` used by ``WH_MOUSE_LL``."""

    _fields_ = [
        ("pt", ctypes.wintypes.POINT),
        ("mouseData", ctypes.wintypes.DWORD),
        ("flags", ctypes.wintypes.DWORD),
        ("time", ctypes.wintypes.DWORD),
        ("dwExtraInfo", ctypes.POINTER(ctypes.c_ulong)),
    ]


# Callback type for SetWindowsHookExW.
_HOOKPROC = ctypes.WINFUNCTYPE(
    ctypes.wintypes.LPARAM,  # return type
    ctypes.c_int,            # nCode
    ctypes.wintypes.WPARAM,  # wParam
    ctypes.wintypes.LPARAM,  # lParam
)


class MouseBlocker:
    """Block physical mouse events while allowing injected (simulated) ones.

    Uses a ``WH_MOUSE_LL`` hook that inspects the ``LLMHF_INJECTED`` flag.
    Events generated by ``pyautogui`` (which calls ``SendInput``) are marked as
    injected and are allowed through; events from the physical mouse are blocked.

    The hook runs on a dedicated daemon thread with its own Windows message
    loop — this is a requirement for low-level hooks.

    Only functional on Windows; calls are no-ops on other platforms.
    """

    def __init__(self) -> None:
        self._hook_handle: Optional[int] = None
        self._thread: Optional[threading.Thread] = None
        self._is_blocking = False
        self._lock = threading.Lock()
        # Must keep a reference to prevent garbage collection while the hook
        # is installed.
        self._hook_proc: Optional[_HOOKPROC] = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def block(self) -> None:
        """Start blocking physical mouse events."""
        if platform.system() != "Windows":
            logger.warning("MouseBlocker is only supported on Windows")
            return

        with self._lock:
            if self._is_blocking:
                logger.debug("Mouse is already blocked")
                return
            self._is_blocking = True

        self._thread = threading.Thread(
            target=self._run_hook, daemon=True, name="MouseBlockerHook"
        )
        self._thread.start()
        logger.info("Physical mouse input blocked")

    def unblock(self) -> None:
        """Stop blocking physical mouse events and restore normal input."""
        with self._lock:
            if not self._is_blocking:
                return
            self._is_blocking = False

        # Post WM_QUIT to the hook thread's message loop so it exits cleanly.
        if self._thread and self._thread.is_alive():
            thread_id = self._thread.ident
            if thread_id:
                ctypes.windll.user32.PostThreadMessageW(
                    thread_id, 0x0012, 0, 0  # WM_QUIT
                )
            self._thread.join(timeout=3)

        self._thread = None
        self._hook_proc = None
        logger.info("Physical mouse input restored")

    @property
    def is_blocking(self) -> bool:
        """Whether the blocker is currently active."""
        with self._lock:
            return self._is_blocking

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _run_hook(self) -> None:
        """Install the hook and pump messages until told to stop."""
        user32 = ctypes.windll.user32

        def _low_level_mouse_proc(n_code, w_param, l_param):
            """Hook callback: block physical events, allow injected ones."""
            if n_code == 0:  # HC_ACTION
                mouse_struct = ctypes.cast(
                    l_param, ctypes.POINTER(_MSLLHOOKSTRUCT)
                ).contents
                if not (mouse_struct.flags & LLMHF_INJECTED):
                    # Physical event — block by returning 1 (non-zero)
                    return 1
            return user32.CallNextHookEx(None, n_code, w_param, l_param)

        # Must keep a reference alive for the lifetime of the hook.
        self._hook_proc = _HOOKPROC(_low_level_mouse_proc)

        self._hook_handle = user32.SetWindowsHookExW(
            WH_MOUSE_LL, self._hook_proc, None, 0
        )

        if not self._hook_handle:
            logger.error("Failed to install WH_MOUSE_LL hook")
            with self._lock:
                self._is_blocking = False
            return

        # Run a message loop so Windows delivers hook callbacks.
        msg = ctypes.wintypes.MSG()
        while user32.GetMessageW(ctypes.byref(msg), None, 0, 0) > 0:
            user32.TranslateMessage(ctypes.byref(msg))
            user32.DispatchMessageW(ctypes.byref(msg))

        # Cleanup: unhook when the message loop exits.
        user32.UnhookWindowsHookEx(self._hook_handle)
        self._hook_handle = None


# Module-level singleton so the handler and server can share state.
mouse_blocker = MouseBlocker()

# Global UI state dictionary used to sync button visibility with the Android app
ui_state: dict[str, dict[str, bool]] = {}


def set_ui_state(state: dict[str, dict[str, bool]]) -> None:
    """Update the global UI state broadcasted to remote clients."""
    global ui_state
    ui_state = state


# Shared error message constant to avoid duplication.
X_Y_REQUIRED_ERROR = "x and y parameters are required"


class RemoteControlHandler(BaseHTTPRequestHandler):
    """HTTP request handler for the SnapSolve remote control server.

    Endpoints
    ---------
    GET  /status              — Health-check; returns ``{"status": "running"}``.
    GET  /                    — Lists all available endpoints.
    POST /action              — Triggers a SnapSolve action (capture, cancel, etc.).
    POST /mouse/move          — Moves the cursor to a relative position (0–1 range).
    POST /mouse/click         — Single mouse-button click at the current position.
    POST /mouse/double_click  — Double mouse-button click at the current position.
    POST /mouse/drag_start    — Presses and holds a mouse button (drag begin).
    POST /mouse/drag_end      — Releases the held mouse button (drag end).
    POST /mouse/scroll        — Scrolls the wheel; positive delta = up, negative = down.
    """

    # The live application config dict is injected at server construction time so that
    # action handlers can look up the active profile without re-parsing CLI arguments
    # on every request.
    app_config: dict[str, Any] = {}

    # ------------------------------------------------------------------
    # Response helpers
    # ------------------------------------------------------------------

    def _set_cors_headers(self) -> None:
        """Append permissive CORS headers required by the Android HTTP client."""
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")

    def _send_json_response(self, status_code: int, data: dict) -> None:
        """Serialise *data* to JSON and write it as the HTTP response body."""
        self.send_response(status_code)
        self._set_cors_headers()
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps(data).encode("utf-8"))

    def _send_error_response(self, status_code: int, message: str) -> None:
        """Convenience wrapper that sends a JSON ``{"error": message}`` response."""
        self._send_json_response(status_code, {"error": message})

    # ------------------------------------------------------------------
    # HTTP verb handlers
    # ------------------------------------------------------------------

    def do_OPTIONS(self):  # noqa: N802
        """Handle CORS pre-flight requests."""
        self.send_response(200)
        self._set_cors_headers()
        self.end_headers()

    def do_GET(self):  # noqa: N802
        """Handle GET requests for /status and /."""
        parsed_path = urlparse(self.path)

        if parsed_path.path == "/status":
            self._send_json_response(
                200, {"status": "running", "server": "SnapSolve Remote Control"}
            )
        elif parsed_path.path == "/state":
            self._send_json_response(
                200, {"buttons": ui_state}
            )
        elif parsed_path.path == "/":
            self._send_json_response(
                200,
                {
                    "message": "SnapSolve Remote Control Server",
                    "endpoints": [
                        "/status",
                        "/state",
                        "/action",
                        "/connect",
                        "/disconnect",
                        "/mouse/move",
                        "/mouse/click",
                        "/mouse/double_click",
                        "/mouse/drag_start",
                        "/mouse/drag_end",
                        "/mouse/scroll",
                    ],
                },
            )
        else:
            self._send_error_response(404, "Endpoint not found")

    def do_POST(self):  # noqa: N802
        """Route POST requests to the appropriate handler."""
        parsed_path = urlparse(self.path)

        try:
            content_length = int(self.headers["Content-Length"])
            post_data = self.rfile.read(content_length)
            data = json.loads(post_data.decode("utf-8"))
        except (ValueError, KeyError, TypeError) as exc:
            self._send_error_response(400, f"Invalid JSON data: {exc}")
            return

        routes = {
            "/action": self._handle_action,
            "/connect": self._handle_connect,
            "/disconnect": self._handle_disconnect,
            "/mouse/move": self._handle_mouse_move,
            "/mouse/click": self._handle_mouse_click,
            "/mouse/double_click": self._handle_mouse_double_click,
            "/mouse/drag_start": self._handle_mouse_drag_start,
            "/mouse/drag_end": self._handle_mouse_drag_end,
            "/mouse/scroll": self._handle_mouse_scroll,
        }
        handler = routes.get(parsed_path.path)
        if handler:
            handler(data)
        else:
            self._send_error_response(404, "Endpoint not found")

    # ------------------------------------------------------------------
    # Connect / disconnect handlers
    # ------------------------------------------------------------------

    def _handle_connect(self, _data: dict) -> None:
        """Handle an Android client connecting — block the physical mouse."""
        mouse_blocker.block()
        self._send_json_response(
            200, {"status": "connected", "mouse_blocked": True}
        )
        logger.info("Android client connected — physical mouse blocked")

    def _handle_disconnect(self, _data: dict) -> None:
        """Handle an Android client disconnecting — restore the physical mouse."""
        mouse_blocker.unblock()
        self._send_json_response(
            200, {"status": "disconnected", "mouse_blocked": False}
        )
        logger.info("Android client disconnected — physical mouse restored")

    # ------------------------------------------------------------------
    # Action handler
    # ------------------------------------------------------------------

    def _handle_action(self, data: dict) -> None:
        """Dispatch a named SnapSolve action using the live application config.

        The config is passed in at server construction time (stored on the class) to
        avoid the expensive ``get_config()`` / ``parse_args()`` call on every request.

        Supported actions
        -----------------
        capture, reselect, multi_capture, end_multi_capture, cancel,
        toggle_stitching, cycle_source, toggle_panel, new_chat_session
        """
        action = data.get("action")
        if not action:
            self._send_error_response(400, "Action parameter is required")
            return

        # Import inside the function to avoid circular-import issues at module load.
        from main import (  # noqa: PLC0415
            handle_cancel,
            handle_capture,
            handle_cycle_source,
            handle_end_multi_capture,
            handle_multi_capture,
            handle_new_chat_session,
            handle_reselect,
            handle_toggle_panel,
            handle_toggle_stitching,
        )
        from config.settings import load_profiles, load_prompts  # noqa: PLC0415

        try:
            config = self.__class__.app_config
            profiles = load_profiles()
            prompts = load_prompts()

            active_profile_id = config.get("active_profile_id", "prof1")
            active_profile = next(
                (p for p in profiles if p.get("id") == active_profile_id),
                profiles[0] if profiles else {},
            )

            prompt_id = active_profile.get("prompt_id", "default")
            active_prompt = next(
                (p for p in prompts if p.get("id") == prompt_id),
                prompts[0] if prompts else {},
            )
            active_prompt_text = active_prompt.get(
                "text", "answer the following question quickly and briefly"
            )

            action_map = {
                "capture": lambda: handle_capture(
                    config, active_profile, active_prompt_text
                ),
                "reselect": lambda: handle_reselect(config),
                "multi_capture": lambda: handle_multi_capture(config, active_profile),
                "end_multi_capture": lambda: handle_end_multi_capture(
                    config, active_profile, active_prompt_text
                ),
                "cancel": handle_cancel,
                "toggle_stitching": lambda: handle_toggle_stitching(
                    config, active_profile
                ),
                "cycle_source": lambda: handle_cycle_source(config, active_profile),
                "toggle_panel": handle_toggle_panel,
                "new_chat_session": lambda: handle_new_chat_session(config),
            }

            fn = action_map.get(action)
            if fn is None:
                self._send_error_response(400, f"Unknown action: {action}")
                return

            fn()
            self._send_json_response(200, {"status": "success", "action": action})
            logger.info("Remote control action executed: %s", action)

        except Exception as exc:
            logger.error("Error executing action %s: %s", action, exc)
            self._send_error_response(500, f"Error executing action: {exc}")

    # ------------------------------------------------------------------
    # Mouse handlers
    # ------------------------------------------------------------------

    def _handle_mouse_move(self, data: dict) -> None:
        """Move the cursor by relative coordinates.

        The server receives normalized delta values and scales them
        by the current screen resolution.
        """
        try:
            dx = data.get("dx")
            dy = data.get("dy")
            if dx is None or dy is None:
                self._send_error_response(400, "dx and dy parameters are required")
                return

            screen_width, screen_height = pyautogui.size()
            move_x = int(dx * screen_width)
            move_y = int(dy * screen_height)
            pyautogui.move(move_x, move_y)
            self._send_json_response(
                200, {"status": "success", "action": "move", "dx": move_x, "dy": move_y}
            )

        except Exception as exc:
            logger.error("Error moving mouse: %s", exc)
            self._send_error_response(500, f"Error moving mouse: {exc}")

    def _handle_mouse_click(self, data: dict) -> None:
        """Send a single click with the specified button (``left``, ``right``, or ``middle``)."""
        try:
            button = data.get("button", "left")
            if button == "left":
                pyautogui.click()
            elif button == "right":
                pyautogui.rightClick()
            elif button == "middle":
                pyautogui.middleClick()
            else:
                self._send_error_response(400, f"Unknown button: {button}")
                return
            self._send_json_response(
                200, {"status": "success", "action": "click", "button": button}
            )

        except Exception as exc:
            logger.error("Error clicking mouse: %s", exc)
            self._send_error_response(500, f"Error clicking mouse: {exc}")

    def _handle_mouse_double_click(self, data: dict) -> None:
        """Send a double click with the specified button."""
        try:
            button = data.get("button", "left")
            if button == "left":
                pyautogui.doubleClick()
            elif button == "right":
                pyautogui.rightClick()
                pyautogui.rightClick()
            elif button == "middle":
                pyautogui.middleClick()
                pyautogui.middleClick()
            else:
                self._send_error_response(400, f"Unknown button: {button}")
                return
            self._send_json_response(
                200, {"status": "success", "action": "double_click", "button": button}
            )

        except Exception as exc:
            logger.error("Error double-clicking mouse: %s", exc)
            self._send_error_response(500, f"Error double-clicking mouse: {exc}")

    def _handle_mouse_drag_start(self, data: dict) -> None:
        """Press and hold the left mouse button."""
        try:
            pyautogui.mouseDown()
            self._send_json_response(
                200,
                {
                    "status": "success",
                    "action": "drag_start",
                },
            )

        except Exception as exc:
            logger.error("Error starting drag: %s", exc)
            self._send_error_response(500, f"Error starting drag: {exc}")

    def _handle_mouse_drag_end(self, data: dict) -> None:
        """Release the held mouse button."""
        try:
            pyautogui.mouseUp()
            self._send_json_response(
                200,
                {
                    "status": "success",
                    "action": "drag_end",
                },
            )

        except Exception as exc:
            logger.error("Error ending drag: %s", exc)
            self._send_error_response(500, f"Error ending drag: {exc}")

    def _handle_mouse_scroll(self, data: dict) -> None:
        """Scroll the mouse wheel.

        Parameters
        ----------
        data:
            JSON body with a ``delta`` integer.  Positive values scroll up;
            negative values scroll down.
        """
        try:
            delta = data.get("delta", 1)
            pyautogui.scroll(delta)
            self._send_json_response(
                200, {"status": "success", "action": "scroll", "delta": delta}
            )

        except Exception as exc:
            logger.error("Error scrolling mouse: %s", exc)
            self._send_error_response(500, f"Error scrolling mouse: {exc}")

    def log_message(self, fmt: str, *args) -> None:  # noqa: N802
        """Route BaseHTTPRequestHandler access logs through the standard logger."""
        logger.info("%s - %s", self.address_string(), fmt % args if args else fmt)


class RemoteControlServer:
    """Threaded HTTP server that exposes mouse control and SnapSolve actions over LAN.

    Usage
    -----
    .. code-block:: python

        server = RemoteControlServer(host="0.0.0.0", port=8080, config=app_config)
        server.start()
        # … application runs …
        server.stop()
    """

    def __init__(
        self, host: str = "0.0.0.0", port: int = 8080, config: Optional[dict] = None
    ):
        self.host = host
        self.port = port
        self.server: Optional[HTTPServer] = None
        self.server_thread: Optional[threading.Thread] = None
        self.is_running = False

        # Inject the live config into the handler class so each request can use it
        # without re-parsing CLI arguments.
        RemoteControlHandler.app_config = config or {}

    def start(self) -> None:
        """Bind the socket and start accepting requests in a daemon thread."""
        if self.is_running:
            logger.warning("Remote control server is already running")
            return

        try:
            self.server = HTTPServer((self.host, self.port), RemoteControlHandler)
            self.is_running = True
            self.server_thread = threading.Thread(
                target=self._run_server, daemon=True, name="RemoteControlServer"
            )
            self.server_thread.start()
            logger.info(
                "Remote control server started on http://%s:%s", self.host, self.port
            )
            print(f"Remote control server started on http://{self.host}:{self.port}")

        except Exception as exc:
            logger.error("Failed to start remote control server: %s", exc)
            raise

    def _run_server(self) -> None:
        """Blocking serve loop executed on the daemon thread."""
        assert self.server is not None
        try:
            self.server.serve_forever()
        except Exception as exc:
            logger.error("Server error: %s", exc)
            self.is_running = False

    def stop(self) -> None:
        """Gracefully shut down the server and join the daemon thread."""
        if not self.is_running:
            return

        try:
            # Always restore the physical mouse before shutting down.
            mouse_blocker.unblock()

            self.is_running = False
            if self.server:
                self.server.shutdown()
                self.server.server_close()
            if self.server_thread:
                self.server_thread.join(timeout=5)
            logger.info("Remote control server stopped")

        except Exception as exc:
            logger.error("Error stopping remote control server: %s", exc)


# ---------------------------------------------------------------------------
# Module-level convenience functions
# ---------------------------------------------------------------------------

# Global singleton — one server per process.
remote_control_server: Optional[RemoteControlServer] = None


def start_remote_control_server(
    host: str = "0.0.0.0", port: int = 8080, config: Optional[dict] = None
) -> RemoteControlServer:
    """Create (if needed) and start the global remote control server.

    Parameters
    ----------
    host:   Network interface to bind. Use ``"0.0.0.0"`` to accept connections on
            all interfaces (default).
    port:   TCP port to listen on (default 8080).
    config: The live application config dict. Passed to action handlers so they
            do not need to call ``get_config()`` on every request.

    Returns
    -------
    The running :class:`RemoteControlServer` instance.
    """
    global remote_control_server

    if remote_control_server is None:
        remote_control_server = RemoteControlServer(host, port, config)

    remote_control_server.start()
    return remote_control_server


def stop_remote_control_server() -> None:
    """Stop and discard the global remote control server."""
    global remote_control_server

    if remote_control_server:
        remote_control_server.stop()
        remote_control_server = None
