from __future__ import annotations

import asyncio
import ctypes
import ctypes.wintypes
import json
import logging
import os
import platform
import threading
from typing import Any, Optional

import keyboard
import pyautogui

# Disable pyautogui's default 0.1 s pause after every call — critical for
# real-time mouse control.  Without this the server processes moves at ~10 Hz
# while receiving them at ~30 Hz, causing a huge backlog that drains long
# after the finger lifts.
pyautogui.PAUSE = 0

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Mouse blocker — blocks physical mouse while allowing pyautogui (injected)
# ---------------------------------------------------------------------------

# Windows constants for the low-level mouse hook.
WH_MOUSE_LL = 14
LLMHF_INJECTED = 0x00000001


class _MSLLHOOKSTRUCT(ctypes.Structure):
    """Mirror of the Win32 ``MSLLHOOKSTRUCT`` used by ``WH_MOUSE_LL``."""

    _fields_ = [
        ("pt", ctypes.wintypes.POINT),
        ("mouseData", ctypes.wintypes.DWORD),
        ("flags", ctypes.wintypes.DWORD),
        ("time", ctypes.wintypes.DWORD),
        ("dwExtraInfo", ctypes.POINTER(ctypes.c_ulong)),
    ]


# Callback type for SetWindowsHookExW.
_HOOKPROC = ctypes.WINFUNCTYPE(
    ctypes.wintypes.LPARAM,  # return type
    ctypes.c_int,  # nCode
    ctypes.wintypes.WPARAM,  # wParam
    ctypes.wintypes.LPARAM,  # lParam
)


class MouseBlocker:
    """Block physical mouse events while allowing injected (simulated) ones.

    Uses a ``WH_MOUSE_LL`` hook that inspects the ``LLMHF_INJECTED`` flag.
    Events generated by ``pyautogui`` (which calls ``SendInput``) are marked as
    injected and are allowed through; events from the physical mouse are blocked.

    The hook runs on a dedicated daemon thread with its own Windows message
    loop — this is a requirement for low-level hooks.

    Only functional on Windows; calls are no-ops on other platforms.
    """

    def __init__(self) -> None:
        self._hook_handle: Optional[int] = None
        self._thread: Optional[threading.Thread] = None
        self._is_blocking = False
        self._lock = threading.Lock()
        # Must keep a reference to prevent garbage collection while the hook
        # is installed.
        self._hook_proc: Optional[_HOOKPROC] = None
        self._idle_timer: Optional[threading.Timer] = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def block(self) -> None:
        """Start blocking physical mouse events."""
        if platform.system() != "Windows":
            logger.warning("MouseBlocker is only supported on Windows")
            return

        with self._lock:
            if self._is_blocking:
                logger.debug("Mouse is already blocked")
                return
            self._is_blocking = True

        self._thread = threading.Thread(
            target=self._run_hook, daemon=True, name="MouseBlockerHook"
        )
        self._thread.start()
        logger.info("Physical mouse input blocked")

    def unblock(self) -> None:
        """Stop blocking physical mouse events and restore normal input."""
        with self._lock:
            if self._idle_timer:
                self._idle_timer.cancel()
                self._idle_timer = None
            if not self._is_blocking:
                return
            self._is_blocking = False

        # Post WM_QUIT to the hook thread's message loop so it exits cleanly.
        if self._thread and self._thread.is_alive():
            thread_id = self._thread.ident
            if thread_id:
                ctypes.windll.user32.PostThreadMessageW(
                    thread_id, 0x0012, 0, 0  # WM_QUIT
                )
            self._thread.join(timeout=3)

        self._thread = None
        self._hook_proc = None
        logger.info("Physical mouse input restored")

    @property
    def is_blocking(self) -> bool:
        """Whether the blocker is currently active."""
        with self._lock:
            return self._is_blocking

    def refresh(self, timeout: float) -> None:
        """Refresh the idle timer, blocking the mouse if it was unblocked."""
        with self._lock:
            if self._idle_timer:
                self._idle_timer.cancel()
                self._idle_timer = None

        if not self.is_blocking:
            self.block()

        with self._lock:
            if timeout > 0:
                self._idle_timer = threading.Timer(timeout, self.unblock)
                self._idle_timer.start()

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _run_hook(self) -> None:
        """Install the hook and pump messages until told to stop."""
        user32 = ctypes.windll.user32

        # Define argtypes and restypes to prevent OverflowError on 64-bit systems
        user32.CallNextHookEx.argtypes = [
            ctypes.wintypes.HHOOK,
            ctypes.c_int,
            ctypes.wintypes.WPARAM,
            ctypes.wintypes.LPARAM,
        ]
        user32.CallNextHookEx.restype = ctypes.wintypes.LPARAM

        user32.SetWindowsHookExW.argtypes = [
            ctypes.c_int,
            _HOOKPROC,
            ctypes.wintypes.HINSTANCE,
            ctypes.wintypes.DWORD,
        ]
        user32.SetWindowsHookExW.restype = ctypes.wintypes.HHOOK

        user32.UnhookWindowsHookEx.argtypes = [ctypes.wintypes.HHOOK]
        user32.UnhookWindowsHookEx.restype = ctypes.wintypes.BOOL

        # Scroll wheel messages must pass through unconditionally because
        # pyautogui.scroll() (via mouse_event / SendInput) does not reliably
        # set the LLMHF_INJECTED flag for WM_MOUSEWHEEL on all Windows builds.
        WM_MOUSEWHEEL = 0x020A
        WM_MOUSEHWHEEL = 0x020E

        def _low_level_mouse_proc(n_code, w_param, l_param):
            """Hook callback: block physical events, allow injected ones."""
            if n_code == 0:  # HC_ACTION
                # Always let scroll-wheel events through — the only scroll
                # source during remote control is pyautogui.
                if w_param in (WM_MOUSEWHEEL, WM_MOUSEHWHEEL):
                    return user32.CallNextHookEx(None, n_code, w_param, l_param)
                mouse_struct = ctypes.cast(
                    l_param, ctypes.POINTER(_MSLLHOOKSTRUCT)
                ).contents
                if not (mouse_struct.flags & LLMHF_INJECTED):
                    # Physical event — block by returning 1 (non-zero)
                    return 1
            return user32.CallNextHookEx(None, n_code, w_param, l_param)

        # Must keep a reference alive for the lifetime of the hook.
        self._hook_proc = _HOOKPROC(_low_level_mouse_proc)

        self._hook_handle = user32.SetWindowsHookExW(
            WH_MOUSE_LL, self._hook_proc, None, 0
        )

        if not self._hook_handle:
            logger.error("Failed to install WH_MOUSE_LL hook")
            with self._lock:
                self._is_blocking = False
            return

        # Run a message loop so Windows delivers hook callbacks.
        msg = ctypes.wintypes.MSG()
        while user32.GetMessageW(ctypes.byref(msg), None, 0, 0) > 0:
            user32.TranslateMessage(ctypes.byref(msg))
            user32.DispatchMessageW(ctypes.byref(msg))

        # Cleanup: unhook when the message loop exits.
        user32.UnhookWindowsHookEx(self._hook_handle)
        self._hook_handle = None


# Module-level singleton so the handler and server can share state.
mouse_blocker = MouseBlocker()

# Global UI state dictionary used to sync button visibility with the Android app
ui_state: dict[str, dict[str, bool]] = {}

# Android client connection tracking
_android_client_connected: bool = False

# Latest response image path for sharing with Android
_response_image_path: Optional[str] = None
_has_new_response_image: bool = False
_response_image_lock = threading.Lock()


def set_ui_state(state: dict[str, dict[str, bool]]) -> None:
    """Update the global UI state and push it to the connected remote client."""
    global ui_state
    ui_state = state
    # Push state to connected WebSocket client
    if remote_control_server and remote_control_server.is_running:
        remote_control_server.schedule_push_state(state)


def is_android_connected() -> bool:
    """Check whether an Android client is currently connected."""
    return _android_client_connected


def set_response_image_path(path: str) -> None:
    """Store the path of a new response screenshot and notify the Android client."""
    global _response_image_path, _has_new_response_image
    with _response_image_lock:
        _response_image_path = path
        _has_new_response_image = True
    logger.info("Response image available for Android: %s", path)
    # Notify the connected client via a state_update push
    if remote_control_server and remote_control_server.is_running:
        remote_control_server.schedule_push_state(ui_state)


# ---------------------------------------------------------------------------
# WebSocket message handlers
# ---------------------------------------------------------------------------

def _refresh_idle_timer(app_config: dict[str, Any]) -> None:
    """Refresh the idle timer for the mouse blocker."""
    timeout = app_config.get("remote_mouse_idle_timeout", 3.0)
    mouse_blocker.refresh(timeout)


def _handle_connect(app_config: dict[str, Any]) -> dict:
    """Handle an Android client connecting — block the physical mouse."""
    global _android_client_connected
    _android_client_connected = True
    _refresh_idle_timer(app_config)
    logger.info("Android client connected — physical mouse blocked")
    return {"type": "response", "status": "connected", "mouse_blocked": True}


def _handle_disconnect() -> dict:
    """Handle an Android client disconnecting — restore the physical mouse."""
    global _android_client_connected
    _android_client_connected = False
    mouse_blocker.unblock()
    logger.info("Android client disconnected — physical mouse restored")
    return {"type": "response", "status": "disconnected", "mouse_blocked": False}


def _handle_action(data: dict, app_config: dict[str, Any]) -> dict:
    """Dispatch a named SnapSolve action using the live application config."""
    _refresh_idle_timer(app_config)
    action = data.get("action")
    if not action:
        return {"type": "error", "message": "Action parameter is required"}

    # Import inside the function to avoid circular-import issues at module load.
    from main import (  # noqa: PLC0415
        handle_cancel,
        handle_capture,
        handle_cycle_source,
        handle_end_multi_capture,
        handle_multi_capture,
        handle_new_chat_session,
        handle_reselect,
        handle_toggle_panel,
        handle_toggle_stitching,
    )
    from config.settings import load_profiles, load_prompts  # noqa: PLC0415

    try:
        profiles = load_profiles()
        prompts = load_prompts()

        active_profile_id = app_config.get("active_profile_id", "prof1")
        active_profile = next(
            (p for p in profiles if p.get("id") == active_profile_id),
            profiles[0] if profiles else {},
        )

        prompt_id = active_profile.get("prompt_id", "default")
        active_prompt = next(
            (p for p in prompts if p.get("id") == prompt_id),
            prompts[0] if prompts else {},
        )
        active_prompt_text = active_prompt.get(
            "text", "answer the following question quickly and briefly"
        )

        action_map = {
            "capture": lambda: handle_capture(
                app_config, active_profile, active_prompt_text
            ),
            "reselect": lambda: handle_reselect(app_config),
            "multi_capture": lambda: handle_multi_capture(app_config, active_profile),
            "end_multi_capture": lambda: handle_end_multi_capture(
                app_config, active_profile, active_prompt_text
            ),
            "cancel": handle_cancel,
            "toggle_stitching": lambda: handle_toggle_stitching(
                app_config, active_profile
            ),
            "cycle_source": lambda: handle_cycle_source(app_config, active_profile),
            "toggle_panel": handle_toggle_panel,
            "new_chat_session": lambda: handle_new_chat_session(app_config),
        }

        fn = action_map.get(action)
        if fn is None:
            return {"type": "error", "message": f"Unknown action: {action}"}

        fn()
        logger.info("Remote control action executed: %s", action)
        return {"type": "response", "status": "success", "action": action}

    except Exception as exc:
        logger.error("Error executing action %s: %s", action, exc)
        return {"type": "error", "message": f"Error executing action: {exc}"}


def _handle_mouse_move(data: dict, app_config: dict[str, Any]) -> Optional[dict]:
    """Move the cursor by relative coordinates.

    Returns ``None`` on success (no response sent) to avoid doubling
    WebSocket traffic for high-frequency move events.
    """
    _refresh_idle_timer(app_config)
    try:
        dx = data.get("dx")
        dy = data.get("dy")
        if dx is None or dy is None:
            return {"type": "error", "message": "dx and dy parameters are required"}

        screen_width, screen_height = pyautogui.size()
        sensitivity = app_config.get("mouse_sensitivity", 1.5)
        move_x = int(dx * screen_width * sensitivity)
        move_y = int(dy * screen_height * sensitivity)
        pyautogui.move(move_x, move_y)
        return None  # fire-and-forget — no response needed

    except Exception as exc:
        logger.error("Error moving mouse: %s", exc)
        return {"type": "error", "message": f"Error moving mouse: {exc}"}


def _handle_mouse_click(data: dict, app_config: dict[str, Any]) -> dict:
    """Send a single click with the specified button."""
    _refresh_idle_timer(app_config)
    try:
        button = data.get("button", "left")
        if button == "left":
            pyautogui.click()
        elif button == "right":
            pyautogui.rightClick()
        elif button == "middle":
            pyautogui.middleClick()
        else:
            return {"type": "error", "message": f"Unknown button: {button}"}
        return {"type": "response", "status": "success", "action": "click", "button": button}

    except Exception as exc:
        logger.error("Error clicking mouse: %s", exc)
        return {"type": "error", "message": f"Error clicking mouse: {exc}"}


def _handle_mouse_double_click(data: dict, app_config: dict[str, Any]) -> dict:
    """Send a double click with the specified button."""
    _refresh_idle_timer(app_config)
    try:
        button = data.get("button", "left")
        if button == "left":
            pyautogui.doubleClick()
        elif button == "right":
            pyautogui.rightClick()
            pyautogui.rightClick()
        elif button == "middle":
            pyautogui.middleClick()
            pyautogui.middleClick()
        else:
            return {"type": "error", "message": f"Unknown button: {button}"}
        return {"type": "response", "status": "success", "action": "double_click", "button": button}

    except Exception as exc:
        logger.error("Error double-clicking mouse: %s", exc)
        return {"type": "error", "message": f"Error double-clicking mouse: {exc}"}


def _handle_mouse_drag_start(app_config: dict[str, Any]) -> dict:
    """Press and hold the left mouse button."""
    _refresh_idle_timer(app_config)
    try:
        pyautogui.mouseDown()
        return {"type": "response", "status": "success", "action": "drag_start"}

    except Exception as exc:
        logger.error("Error starting drag: %s", exc)
        return {"type": "error", "message": f"Error starting drag: {exc}"}


def _handle_mouse_drag_end(app_config: dict[str, Any]) -> dict:
    """Release the held mouse button."""
    _refresh_idle_timer(app_config)
    try:
        pyautogui.mouseUp()
        return {"type": "response", "status": "success", "action": "drag_end"}

    except Exception as exc:
        logger.error("Error ending drag: %s", exc)
        return {"type": "error", "message": f"Error ending drag: {exc}"}


def _handle_mouse_scroll(data: dict, app_config: dict[str, Any]) -> dict:
    """Scroll the mouse wheel."""
    _refresh_idle_timer(app_config)
    try:
        delta = data.get("delta", 1)
        # MOUSEEVENTF_WHEEL = 0x0800, WHEEL_DELTA = 120
        ctypes.windll.user32.mouse_event(0x0800, 0, 0, int(delta) * 120, 0)
        return {"type": "response", "status": "success", "action": "scroll", "delta": delta}

    except Exception as exc:
        logger.error("Error scrolling mouse: %s", exc)
        return {"type": "error", "message": f"Error scrolling mouse: {exc}"}


def _handle_keyboard_type(data: dict, app_config: dict[str, Any]) -> dict:
    """Type the given text using the keyboard module."""
    _refresh_idle_timer(app_config)
    try:
        text = data.get("text")
        if text is None:
            return {"type": "error", "message": "text parameter is required"}

        keyboard.write(text)
        keyboard.send("enter")
        return {"type": "response", "status": "success", "action": "type_text"}
    except Exception as exc:
        logger.error("Error typing text: %s", exc)
        return {"type": "error", "message": f"Error typing text: {exc}"}


def _handle_response_image_ack() -> dict:
    """Acknowledge receipt of the response image and clear the flag."""
    global _has_new_response_image
    with _response_image_lock:
        _has_new_response_image = False
    logger.info("Android client acknowledged response image")
    return {"type": "response", "status": "acknowledged"}


def _handle_set_transcription_language(data: dict, app_config: dict[str, Any]) -> dict:
    """Set the transcription language from the Android client."""
    lang = data.get("language", "en")
    app_config["transcription_language"] = lang
    try:
        from config.settings import save_config  # noqa: PLC0415
        save_config(app_config)
    except Exception as exc:
        logger.error("Failed to save config after language change: %s", exc)
    # Also update the panel combo on the main thread
    from core.output import ui_signals  # noqa: PLC0415
    ui_signals.set_transcription_language.emit(lang)
    logger.info("Transcription language set to '%s' via remote control", lang)
    return {"type": "response", "status": "success", "action": "set_transcription_language", "language": lang}


# ---------------------------------------------------------------------------
# WebSocket server
# ---------------------------------------------------------------------------

class RemoteControlServer:
    """WebSocket server that exposes mouse control and SnapSolve actions over LAN.

    Plain HTTP ``GET`` requests for ``/status`` and ``/response_image`` are
    intercepted before the WebSocket upgrade via the ``process_request`` hook,
    so the Android client can health-check and fetch response screenshots
    without opening a WebSocket connection.

    Usage
    -----
    .. code-block:: python

        server = RemoteControlServer(host="0.0.0.0", port=8080, config=app_config)
        server.start()
        # … application runs …
        server.stop()
    """

    def __init__(
            self, host: str = "0.0.0.0", port: int = 8080, config: Optional[dict] = None
    ):
        self.host = host
        self.port = port
        self.app_config: dict[str, Any] = config or {}
        self.is_running = False

        # asyncio event loop for the WebSocket server (runs on a background thread)
        self._loop: Optional[asyncio.AbstractEventLoop] = None
        self._server_thread: Optional[threading.Thread] = None
        self._ws_server: Optional[Any] = None  # websockets.WebSocketServer

        # Single connected client (only one allowed at a time)
        self._client: Optional[Any] = None  # websockets.ServerConnection
        self._client_lock = threading.Lock()

    def start(self) -> None:
        """Start the WebSocket server on a daemon thread."""
        if self.is_running:
            logger.warning("Remote control server is already running")
            return

        try:
            self._loop = asyncio.new_event_loop()
            self.is_running = True
            self._server_thread = threading.Thread(
                target=self._run_server, daemon=True, name="RemoteControlServer"
            )
            self._server_thread.start()
            logger.info(
                "Remote control server starting on ws://%s:%s", self.host, self.port
            )
            print(f"Remote control server starting on ws://{self.host}:{self.port}")

        except Exception as exc:
            logger.error("Failed to start remote control server: %s", exc)
            raise

    def _run_server(self) -> None:
        """Blocking server loop executed on the daemon thread."""
        assert self._loop is not None
        asyncio.set_event_loop(self._loop)
        try:
            self._loop.run_until_complete(self._serve())
        except Exception as exc:
            logger.error("Server error: %s", exc)
            self.is_running = False

    async def _serve(self) -> None:
        """Start the WebSocket server and run until stopped."""
        import websockets  # noqa: PLC0415

        self._ws_server = await websockets.serve(
            self._handler,
            self.host,
            self.port,
            process_request=self._process_http_request,
            ping_interval=20,
            ping_timeout=10,
        )
        logger.info("Remote control WebSocket server is ready on ws://%s:%s", self.host, self.port)
        print(f"Remote control WebSocket server ready on ws://{self.host}:{self.port}")

        # Block until the server is closed
        await self._ws_server.wait_closed()

    # ------------------------------------------------------------------
    # HTTP request interception (for /status and /response_image)
    # ------------------------------------------------------------------

    def _process_http_request(self, connection, request):
        """Intercept plain HTTP requests before the WebSocket handshake.

        Returns an HTTP ``Response`` for ``/status`` and ``/response_image``
        endpoints so the Android client can health-check the server and
        fetch response screenshots over plain HTTP.  Returns ``None`` for
        all other paths to proceed with the normal WebSocket upgrade.
        """
        from websockets.datastructures import Headers as WsHeaders  # noqa: PLC0415
        from websockets.http11 import Response as WsResponse  # noqa: PLC0415

        if request.path == "/status":
            body = json.dumps(
                {"status": "running", "server": "SnapSolve Remote Control"}
            ).encode("utf-8")
            return WsResponse(
                200, "OK",
                WsHeaders([("Content-Type", "application/json"), ("Access-Control-Allow-Origin", "*")]),
                body,
            )

        if request.path == "/response_image":
            return self._serve_response_image_http(WsResponse, WsHeaders)

        # Return None → proceed with WebSocket upgrade
        return None

    @staticmethod
    def _serve_response_image_http(ws_response_cls, ws_headers_cls):
        """Build an HTTP response containing the latest response screenshot."""
        with _response_image_lock:
            image_path = _response_image_path

        if not image_path or not os.path.exists(image_path):
            body = json.dumps({"error": "No response image available"}).encode("utf-8")
            return ws_response_cls(
                404, "Not Found",
                ws_headers_cls([("Content-Type", "application/json"), ("Access-Control-Allow-Origin", "*")]),
                body,
            )

        try:
            with open(image_path, "rb") as f:
                image_data = f.read()
            return ws_response_cls(
                200, "OK",
                ws_headers_cls([
                    ("Content-Type", "image/png"),
                    ("Content-Length", str(len(image_data))),
                    ("Access-Control-Allow-Origin", "*"),
                ]),
                image_data,
            )
        except Exception as exc:
            logger.error("Error serving response image: %s", exc)
            body = json.dumps({"error": f"Error serving image: {exc}"}).encode("utf-8")
            return ws_response_cls(
                500, "Internal Server Error",
                ws_headers_cls([("Content-Type", "application/json"), ("Access-Control-Allow-Origin", "*")]),
                body,
            )

    # ------------------------------------------------------------------
    # WebSocket connection handler
    # ------------------------------------------------------------------

    async def _handler(self, websocket) -> None:
        """Per-connection handler — only one client is allowed at a time."""
        global _android_client_connected

        # Reject if another client is already connected.
        with self._client_lock:
            if self._client is not None:
                await websocket.close(1013, "Another client is already connected")
                logger.warning(
                    "Rejected WebSocket client from %s — another client is already connected",
                    websocket.remote_address,
                )
                return
            self._client = websocket

        logger.info("WebSocket client connected from %s", websocket.remote_address)

        try:
            async for raw_message in websocket:
                # Drain all immediately-available messages so we can
                # coalesce high-frequency mouse_move events and skip
                # stale intermediate positions.
                pending_raw = [raw_message]
                while True:
                    try:
                        extra = await asyncio.wait_for(websocket.recv(), timeout=0.001)
                        pending_raw.append(extra)
                    except (asyncio.TimeoutError, Exception):
                        break

                # Parse and separate: keep only the latest mouse_move,
                # preserve order of everything else.
                latest_move: Optional[dict] = None
                other_messages: list[dict] = []
                for raw in pending_raw:
                    try:
                        data = json.loads(raw)
                    except (json.JSONDecodeError, TypeError) as exc:
                        await websocket.send(json.dumps(
                            {"type": "error", "message": f"Invalid JSON: {exc}"}
                        ))
                        continue
                    if data.get("type") == "mouse_move":
                        latest_move = data  # overwrite — only the newest matters
                    else:
                        other_messages.append(data)

                # Execute non-move messages in order
                for data in other_messages:
                    response = self._dispatch(data)
                    if response:
                        await websocket.send(json.dumps(response))

                # Execute the single latest move (if any)
                if latest_move is not None:
                    response = self._dispatch(latest_move)
                    if response:
                        await websocket.send(json.dumps(response))

        except Exception as exc:
            logger.debug("WebSocket connection error: %s", exc)
        finally:
            with self._client_lock:
                if self._client is websocket:
                    self._client = None

            _android_client_connected = False
            mouse_blocker.unblock()
            logger.info("WebSocket client disconnected — physical mouse restored")

    def _dispatch(self, data: dict) -> Optional[dict]:
        """Route an incoming message to the appropriate handler by ``type``."""
        msg_type = data.get("type")
        if not msg_type:
            return {"type": "error", "message": "Missing 'type' field"}

        handlers = {
            "connect": lambda: _handle_connect(self.app_config),
            "disconnect": lambda: _handle_disconnect(),
            "action": lambda: _handle_action(data, self.app_config),
            "mouse_move": lambda: _handle_mouse_move(data, self.app_config),
            "mouse_click": lambda: _handle_mouse_click(data, self.app_config),
            "mouse_double_click": lambda: _handle_mouse_double_click(data, self.app_config),
            "mouse_drag_start": lambda: _handle_mouse_drag_start(self.app_config),
            "mouse_drag_end": lambda: _handle_mouse_drag_end(self.app_config),
            "mouse_scroll": lambda: _handle_mouse_scroll(data, self.app_config),
            "keyboard_type": lambda: _handle_keyboard_type(data, self.app_config),
            "response_image_ack": lambda: _handle_response_image_ack(),
            "set_transcription_language": lambda: _handle_set_transcription_language(
                data, self.app_config
            ),
        }

        handler = handlers.get(msg_type)
        if handler is None:
            return {"type": "error", "message": f"Unknown message type: {msg_type}"}

        return handler()

    # ------------------------------------------------------------------
    # Server-push methods (called from other threads)
    # ------------------------------------------------------------------

    def schedule_push_state(self, state: dict[str, dict[str, bool]]) -> None:
        """Schedule a UI state push to the connected client (thread-safe)."""
        if self._loop and self.is_running:
            asyncio.run_coroutine_threadsafe(
                self._push_state(state), self._loop
            )

    async def _push_state(self, state: dict[str, dict[str, bool]]) -> None:
        """Push a ``state_update`` message to the connected client."""
        with self._client_lock:
            client = self._client

        if client is None:
            return

        with _response_image_lock:
            has_image = _has_new_response_image

        message = json.dumps({
            "type": "state_update",
            "buttons": state,
            "has_new_response_image": has_image,
            "transcription_language": self.app_config.get("transcription_language", "en"),
        })

        try:
            await client.send(message)
        except Exception:
            pass  # Client may have disconnected

    # ------------------------------------------------------------------
    # Shutdown
    # ------------------------------------------------------------------

    def stop(self) -> None:
        """Gracefully shut down the server and join the daemon thread."""
        if not self.is_running:
            return

        try:
            # Always restore the physical mouse before shutting down.
            mouse_blocker.unblock()

            self.is_running = False

            if self._ws_server and self._loop:
                # Close the server from the event loop thread
                async def _shutdown():
                    self._ws_server.close()
                    await self._ws_server.wait_closed()

                future = asyncio.run_coroutine_threadsafe(_shutdown(), self._loop)
                try:
                    future.result(timeout=5)
                except Exception:
                    pass

                # Stop the event loop
                self._loop.call_soon_threadsafe(self._loop.stop)

            if self._server_thread:
                self._server_thread.join(timeout=5)

            logger.info("Remote control server stopped")

        except Exception as exc:
            logger.error("Error stopping remote control server: %s", exc)


# ---------------------------------------------------------------------------
# Module-level convenience functions
# ---------------------------------------------------------------------------

# Global singleton — one server per process.
remote_control_server: Optional[RemoteControlServer] = None


def start_remote_control_server(
        host: str = "0.0.0.0", port: int = 8080, config: Optional[dict] = None
) -> RemoteControlServer:
    """Create (if needed) and start the global remote control server.

    Parameters
    ----------
    host:   Network interface to bind. Use ``"0.0.0.0"`` to accept connections on
            all interfaces (default).
    port:   TCP port to listen on (default 8080).
    config: The live application config dict. Passed to action handlers so they
            do not need to call ``get_config()`` on every request.

    Returns
    -------
    The running :class:`RemoteControlServer` instance.
    """
    global remote_control_server

    if remote_control_server is None:
        remote_control_server = RemoteControlServer(host, port, config)

    remote_control_server.start()
    return remote_control_server


def stop_remote_control_server() -> None:
    """Stop and discard the global remote control server."""
    global remote_control_server

    if remote_control_server:
        remote_control_server.stop()
        remote_control_server = None
