from __future__ import annotations

import asyncio
import ctypes
import ctypes.wintypes
import json
import logging
import os
import platform
import threading
from typing import Any, Optional

import keyboard
import pyautogui

# Disable pyautogui's default 0.1 s pause after every call — critical for
# real-time mouse control.  Without this the server processes moves at ~10 Hz
# while receiving them at ~30 Hz, causing a huge backlog that drains long
# after the finger lifts.
pyautogui.PAUSE = 0

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Mouse blocker — blocks physical mouse while allowing pyautogui (injected)
# ---------------------------------------------------------------------------

# Windows constants for the low-level mouse hook.
WH_MOUSE_LL = 14
LLMHF_INJECTED = 0x00000001


class _MSLLHOOKSTRUCT(ctypes.Structure):
    """Mirror of the Win32 ``MSLLHOOKSTRUCT`` used by ``WH_MOUSE_LL``."""

    _fields_ = [
        ("pt", ctypes.wintypes.POINT),
        ("mouseData", ctypes.wintypes.DWORD),
        ("flags", ctypes.wintypes.DWORD),
        ("time", ctypes.wintypes.DWORD),
        ("dwExtraInfo", ctypes.POINTER(ctypes.c_ulong)),
    ]


# Callback type for SetWindowsHookExW.
_HOOKPROC = ctypes.WINFUNCTYPE(
    ctypes.wintypes.LPARAM,  # return type
    ctypes.c_int,  # nCode
    ctypes.wintypes.WPARAM,  # wParam
    ctypes.wintypes.LPARAM,  # lParam
)


class MouseBlocker:
    """Block physical mouse events while allowing injected (simulated) ones.

    Uses a ``WH_MOUSE_LL`` hook that inspects the ``LLMHF_INJECTED`` flag.
    Events generated by ``pyautogui`` (which calls ``SendInput``) are marked as
    injected and are allowed through; events from the physical mouse are blocked.

    The hook runs on a dedicated daemon thread with its own Windows message
    loop — this is a requirement for low-level hooks.

    Only functional on Windows; calls are no-ops on other platforms.
    """

    def __init__(self) -> None:
        self._hook_handle: Optional[int] = None
        self._thread: Optional[threading.Thread] = None
        self._is_blocking = False
        self._lock = threading.Lock()
        # Must keep a reference to prevent garbage collection while the hook
        # is installed.
        self._hook_proc: Optional[_HOOKPROC] = None
        self._idle_timer: Optional[threading.Timer] = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def block(self) -> None:
        """Start blocking physical mouse events."""
        if platform.system() != "Windows":
            logger.warning("MouseBlocker is only supported on Windows")
            return

        with self._lock:
            if self._is_blocking:
                logger.debug("Mouse is already blocked")
                return
            self._is_blocking = True

        self._thread = threading.Thread(
            target=self._run_hook, daemon=True, name="MouseBlockerHook"
        )
        self._thread.start()
        logger.info("Physical mouse input blocked")

    def unblock(self) -> None:
        """Stop blocking physical mouse events and restore normal input."""
        with self._lock:
            if self._idle_timer:
                self._idle_timer.cancel()
                self._idle_timer = None
            if not self._is_blocking:
                return
            self._is_blocking = False

        # Post WM_QUIT to the hook thread's message loop so it exits cleanly.
        if self._thread and self._thread.is_alive():
            thread_id = self._thread.ident
            if thread_id:
                ctypes.windll.user32.PostThreadMessageW(
                    thread_id, 0x0012, 0, 0  # WM_QUIT
                )
            self._thread.join(timeout=3)

        self._thread = None
        self._hook_proc = None
        logger.info("Physical mouse input restored")

    @property
    def is_blocking(self) -> bool:
        """Whether the blocker is currently active."""
        with self._lock:
            return self._is_blocking

    def refresh(self, timeout: float) -> None:
        """Refresh the idle timer, blocking the mouse if it was unblocked."""
        with self._lock:
            if self._idle_timer:
                self._idle_timer.cancel()
                self._idle_timer = None

        if not self.is_blocking:
            self.block()

        with self._lock:
            if timeout > 0:
                self._idle_timer = threading.Timer(timeout, self.unblock)
                self._idle_timer.start()

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _run_hook(self) -> None:
        """Install the hook and pump messages until told to stop."""
        user32 = ctypes.windll.user32

        # Define argtypes and restypes to prevent OverflowError on 64-bit systems
        user32.CallNextHookEx.argtypes = [
            ctypes.wintypes.HHOOK,
            ctypes.c_int,
            ctypes.wintypes.WPARAM,
            ctypes.wintypes.LPARAM,
        ]
        user32.CallNextHookEx.restype = ctypes.wintypes.LPARAM

        user32.SetWindowsHookExW.argtypes = [
            ctypes.c_int,
            _HOOKPROC,
            ctypes.wintypes.HINSTANCE,
            ctypes.wintypes.DWORD,
        ]
        user32.SetWindowsHookExW.restype = ctypes.wintypes.HHOOK

        user32.UnhookWindowsHookEx.argtypes = [ctypes.wintypes.HHOOK]
        user32.UnhookWindowsHookEx.restype = ctypes.wintypes.BOOL

        # Scroll wheel messages must pass through unconditionally because
        # pyautogui.scroll() (via mouse_event / SendInput) does not reliably
        # set the LLMHF_INJECTED flag for WM_MOUSEWHEEL on all Windows builds.
        WM_MOUSEWHEEL = 0x020A
        WM_MOUSEHWHEEL = 0x020E

        def _low_level_mouse_proc(n_code, w_param, l_param):
            """Hook callback: block physical events, allow injected ones."""
            if n_code == 0:  # HC_ACTION
                # Always let scroll-wheel events through — the only scroll
                # source during remote control is pyautogui.
                if w_param in (WM_MOUSEWHEEL, WM_MOUSEHWHEEL):
                    return user32.CallNextHookEx(None, n_code, w_param, l_param)
                mouse_struct = ctypes.cast(
                    l_param, ctypes.POINTER(_MSLLHOOKSTRUCT)
                ).contents
                if not (mouse_struct.flags & LLMHF_INJECTED):
                    # Physical event — block by returning 1 (non-zero)
                    return 1
            return user32.CallNextHookEx(None, n_code, w_param, l_param)

        # Must keep a reference alive for the lifetime of the hook.
        self._hook_proc = _HOOKPROC(_low_level_mouse_proc)

        self._hook_handle = user32.SetWindowsHookExW(
            WH_MOUSE_LL, self._hook_proc, None, 0
        )

        if not self._hook_handle:
            logger.error("Failed to install WH_MOUSE_LL hook")
            with self._lock:
                self._is_blocking = False
            return

        # Run a message loop so Windows delivers hook callbacks.
        msg = ctypes.wintypes.MSG()
        while user32.GetMessageW(ctypes.byref(msg), None, 0, 0) > 0:
            user32.TranslateMessage(ctypes.byref(msg))
            user32.DispatchMessageW(ctypes.byref(msg))

        # Cleanup: unhook when the message loop exits.
        user32.UnhookWindowsHookEx(self._hook_handle)
        self._hook_handle = None


# Module-level singleton so the handler and server can share state.
mouse_blocker = MouseBlocker()

# Global UI state dictionary used to sync button visibility with the Android app
ui_state: dict[str, dict[str, bool]] = {}

# Android client connection tracking
_android_client_connected: bool = False

# Latest response image path for sharing with Android
_response_image_path: Optional[str] = None
_has_new_response_image: bool = False
_response_image_lock = threading.Lock()


def set_ui_state(state: dict[str, dict[str, bool]]) -> None:
    """Update the global UI state and push it to the connected remote client."""
    global ui_state
    ui_state = state
    # Push state to connected WebSocket client
    from core.api_server import api_server_instance
    if api_server_instance and api_server_instance.is_running:
        api_server_instance.schedule_push_state(state)


def is_android_connected() -> bool:
    """Check whether an Android client is currently connected."""
    return _android_client_connected


def set_response_image_path(path: str) -> None:
    """Store the path of a new response screenshot and notify the Android client."""
    global _response_image_path, _has_new_response_image
    with _response_image_lock:
        _response_image_path = path
        _has_new_response_image = True
    logger.info("Response image available for Android: %s", path)
    # Notify the connected client via a state_update push
    from core.api_server import api_server_instance
    if api_server_instance and api_server_instance.is_running:
        api_server_instance.schedule_push_state(ui_state)


# ---------------------------------------------------------------------------
# WebSocket message handlers
# ---------------------------------------------------------------------------

def _refresh_idle_timer(app_config: dict[str, Any]) -> None:
    """Refresh the idle timer for the mouse blocker."""
    timeout = app_config.get("remote_mouse_idle_timeout", 3.0)
    mouse_blocker.refresh(timeout)


def _handle_connect(app_config: dict[str, Any]) -> dict:
    """Handle an Android client connecting — block the physical mouse."""
    global _android_client_connected
    _android_client_connected = True
    _refresh_idle_timer(app_config)
    logger.info("Android client connected — physical mouse blocked")
    return {"type": "response", "status": "connected", "mouse_blocked": True}


def _handle_disconnect() -> dict:
    """Handle an Android client disconnecting — restore the physical mouse."""
    global _android_client_connected
    _android_client_connected = False
    mouse_blocker.unblock()
    logger.info("Android client disconnected — physical mouse restored")
    return {"type": "response", "status": "disconnected", "mouse_blocked": False}


def _handle_action(data: dict, app_config: dict[str, Any]) -> dict:
    """Dispatch a named SnapSolve action using the live application config."""
    _refresh_idle_timer(app_config)
    action = data.get("action")
    if not action:
        return {"type": "error", "message": "Action parameter is required"}

    # Import inside the function to avoid circular-import issues at module load.
    from app.handlers import (  # noqa: PLC0415
        handle_cancel,
        handle_capture,
        handle_cycle_source,
        handle_end_multi_capture,
        handle_multi_capture,
        handle_new_chat_session,
        handle_reselect,
        handle_toggle_panel,
        handle_toggle_chat_sessions,
        handle_toggle_periodic_screenshots,
    )
    from config.settings import load_profiles, load_prompts  # noqa: PLC0415

    try:
        profiles = load_profiles()
        prompts = load_prompts()

        active_profile_id = app_config.get("active_profile_id", "prof1")
        active_profile = next(
            (p for p in profiles if p.get("id") == active_profile_id),
            profiles[0] if profiles else {},
        )

        prompt_id = active_profile.get("prompt_id", "default")
        active_prompt = next(
            (p for p in prompts if p.get("id") == prompt_id),
            prompts[0] if prompts else {},
        )
        active_prompt_text = active_prompt.get(
            "text", "answer the following question quickly and briefly"
        )

        action_map = {
            "capture": lambda: handle_capture(
                app_config, active_profile, active_prompt_text
            ),
            "reselect": lambda: handle_reselect(app_config),
            "multi_capture": lambda: handle_multi_capture(app_config, active_profile),
            "end_multi_capture": lambda: handle_end_multi_capture(
                app_config, active_profile, active_prompt_text
            ),
            "cancel": handle_cancel,
            "toggle_chat_sessions": lambda: handle_toggle_chat_sessions(
                app_config, active_profile
            ),
            "cycle_source": lambda: handle_cycle_source(app_config, active_profile),
            "toggle_panel": handle_toggle_panel,
            "new_chat_session": lambda: handle_new_chat_session(app_config),
            "toggle_periodic_screenshots": lambda: handle_toggle_periodic_screenshots(app_config),
        }

        fn = action_map.get(action)
        if fn is None:
            return {"type": "error", "message": f"Unknown action: {action}"}

        fn()
        logger.info("Remote control action executed: %s", action)
        return {"type": "response", "status": "success", "action": action}

    except Exception as exc:
        logger.error("Error executing action %s: %s", action, exc)
        return {"type": "error", "message": f"Error executing action: {exc}"}


def _handle_mouse_move(data: dict, app_config: dict[str, Any]) -> Optional[dict]:
    """Move the cursor by relative coordinates.

    Returns ``None`` on success (no response sent) to avoid doubling
    WebSocket traffic for high-frequency move events.
    """
    _refresh_idle_timer(app_config)
    try:
        dx = data.get("dx")
        dy = data.get("dy")
        if dx is None or dy is None:
            return {"type": "error", "message": "dx and dy parameters are required"}

        screen_width, screen_height = pyautogui.size()
        sensitivity = app_config.get("mouse_sensitivity", 1.5)
        move_x = int(dx * screen_width * sensitivity)
        move_y = int(dy * screen_height * sensitivity)
        pyautogui.move(move_x, move_y)
        return None  # fire-and-forget — no response needed

    except Exception as exc:
        logger.error("Error moving mouse: %s", exc)
        return {"type": "error", "message": f"Error moving mouse: {exc}"}


def _handle_mouse_click(data: dict, app_config: dict[str, Any]) -> dict:
    """Send a single click with the specified button."""
    _refresh_idle_timer(app_config)
    try:
        button = data.get("button", "left")
        if button == "left":
            pyautogui.click()
        elif button == "right":
            pyautogui.rightClick()
        elif button == "middle":
            pyautogui.middleClick()
        else:
            return {"type": "error", "message": f"Unknown button: {button}"}
        return {"type": "response", "status": "success", "action": "click", "button": button}

    except Exception as exc:
        logger.error("Error clicking mouse: %s", exc)
        return {"type": "error", "message": f"Error clicking mouse: {exc}"}


def _handle_mouse_double_click(data: dict, app_config: dict[str, Any]) -> dict:
    """Send a double click with the specified button."""
    _refresh_idle_timer(app_config)
    try:
        button = data.get("button", "left")
        if button == "left":
            pyautogui.doubleClick()
        elif button == "right":
            pyautogui.rightClick()
            pyautogui.rightClick()
        elif button == "middle":
            pyautogui.middleClick()
            pyautogui.middleClick()
        else:
            return {"type": "error", "message": f"Unknown button: {button}"}
        return {"type": "response", "status": "success", "action": "double_click", "button": button}

    except Exception as exc:
        logger.error("Error double-clicking mouse: %s", exc)
        return {"type": "error", "message": f"Error double-clicking mouse: {exc}"}


def _handle_mouse_drag_start(app_config: dict[str, Any]) -> dict:
    """Press and hold the left mouse button."""
    _refresh_idle_timer(app_config)
    try:
        pyautogui.mouseDown()
        return {"type": "response", "status": "success", "action": "drag_start"}

    except Exception as exc:
        logger.error("Error starting drag: %s", exc)
        return {"type": "error", "message": f"Error starting drag: {exc}"}


def _handle_mouse_drag_end(app_config: dict[str, Any]) -> dict:
    """Release the held mouse button."""
    _refresh_idle_timer(app_config)
    try:
        pyautogui.mouseUp()
        return {"type": "response", "status": "success", "action": "drag_end"}

    except Exception as exc:
        logger.error("Error ending drag: %s", exc)
        return {"type": "error", "message": f"Error ending drag: {exc}"}


def _handle_mouse_scroll(data: dict, app_config: dict[str, Any]) -> dict:
    """Scroll the mouse wheel."""
    _refresh_idle_timer(app_config)
    try:
        delta = data.get("delta", 1)
        # MOUSEEVENTF_WHEEL = 0x0800, WHEEL_DELTA = 120
        ctypes.windll.user32.mouse_event(0x0800, 0, 0, int(delta) * 120, 0)
        return {"type": "response", "status": "success", "action": "scroll", "delta": delta}

    except Exception as exc:
        logger.error("Error scrolling mouse: %s", exc)
        return {"type": "error", "message": f"Error scrolling mouse: {exc}"}


def _handle_keyboard_type(data: dict, app_config: dict[str, Any]) -> dict:
    """Type the given text using the keyboard module."""
    _refresh_idle_timer(app_config)
    try:
        text = data.get("text")
        if text is None:
            return {"type": "error", "message": "text parameter is required"}

        keyboard.write(text)
        keyboard.send("enter")
        return {"type": "response", "status": "success", "action": "type_text"}
    except Exception as exc:
        logger.error("Error typing text: %s", exc)
        return {"type": "error", "message": f"Error typing text: {exc}"}


def _handle_response_image_ack() -> dict:
    """Acknowledge receipt of the response image and clear the flag."""
    global _has_new_response_image
    with _response_image_lock:
        _has_new_response_image = False
    logger.info("Android client acknowledged response image")
    return {"type": "response", "status": "acknowledged"}


def _handle_set_transcription_language(data: dict, app_config: dict[str, Any]) -> dict:
    """Set the transcription language from the Android client."""
    lang = data.get("language", "en")
    app_config["transcription_language"] = lang
    try:
        from config.settings import save_config  # noqa: PLC0415
        save_config(app_config)
    except Exception as exc:
        logger.error("Failed to save config after language change: %s", exc)
    # Also update the panel combo on the main thread
    from core.output import ui_signals  # noqa: PLC0415
    ui_signals.set_transcription_language.emit(lang)
    logger.info("Transcription language set to '%s' via remote control", lang)
    return {"type": "response", "status": "success", "action": "set_transcription_language", "language": lang}


# The websocket server implementation has been moved to api_server.py
